extends: '@absolunet/core'

env:
  node: true
  browser: true

parserOptions:
  sourceType: module

globals:
  window: true
  test: true
  describe: true
  expect: true

rules:
  class-methods-use-this: [off]
  no-restricted-globals: [off]
